<!-- break -->
<br>
<br>
<br>
<!-- break -->

# Langebio Faculty Retreat 2018 

The retreat will take place at Sala Caracol in Langebio. Refreshements and coffee will be provided during the day. Lunch will be by ourselves. Dinner will be at the [Hotsson hotel](https://www.google.com.mx/maps/place/Hotel+Hotsson+Irapuato/@20.7153206,-101.3500749,15z/data=!4m7!3m6!1s0x0:0x22904b2d4884cc61!5m1!1s2018-05-26!8m2!3d20.7153206!4d-101.3500749) in Irapuato. 

We have 8 speakers this year. We have allocated a maximum of 1 hour per speaker including disccussion. Interactive presentations between the speaker and the audience and constructive criticism are highly encouraged. See below the scheduled sessions. 

09:00 - 10:00 **Paco Barona** Integrative Biology @EvoDivMet: a pretention, a possibility or a fact?  
10:00 - 11:00 **Angélica Cibrián** Cycad evolution: genomic insights from the roots up  

11:00 - 11:15 Recess  

11:15 - 12:15 **Ruairidh Sawers** Agrigenomics: Los patos les tiran a las escopetas?  
12:15 - 13:15 **Fabien Plisson** Exploring cysteine-rich peptides and their therapeutic potentials  

13:15 - 15:00 Free time for lunch  

15:00 - 16:00 **Stewart Gillmor** Genome activation and pattern formation in Arabidopsis embryogenesis  
16:00 - 17:00 **Stefan de Folter** Networks guiding gynoecium and fruit development

17:00 - 17:15 Recess  

17:15 - 18:15 **Tania Hernández** Cactus Eco-Evo  
18:15 - 19:15 **Jean Philippe Vielle** Our search for apomixis: the latest  

19:15 - 20:15 Open Discussion  

20:30 - ..:.. Dinner at the Hotsson. 