<!-- break -->
<br>
<!-- break -->

Lab Members
-------------
<!-- break -->
<br>
<!-- break -->
**Allison Barnes** Postdoc.   
Allison joined the lab in NCSU in June 2019. Among other things she is working in the functional characterization of a maize phospholipase.  
<a href="https://twitter.com/asiekmanbarnes">
<i class="fa fa-twitter" aria-hidden="true"></i>
</a>  

**Andi Kur** PhD Student. NCSU Genetics program. AgBioFews Program.   
Andi joined the lab in August 2020. Andi did a Masters at the University of Vermont and UC Davis working on the population genetics of African maize adaptation to New England. She will continue working on landrace local adaptation using a variety of mapping populations.  
<a href="https://twitter.com/Andi_Kur_">
<i class="fa fa-twitter" aria-hidden="true"></i>
</a>  

**Christina Merkel** Lab Tech   
Christina recently got a Biochemistry Major at NCSU and is working with us a lab technician. 
 
**Rubén Rellán-Álvarez. PI**  
Rubén is an Assistant Professor at the Biochemistry Department at CALS - NCSU  
<a href="https://twitter.com/rrellanalvarez">
<i class="fa fa-twitter" aria-hidden="true"></i>
</a>  <a href="https://github.com/rellan">
<i class="fa fa-github-alt" aria-hidden="true"></i>
</a> <a href="mailto:rrellan@ncsu.edu">
<i class="fa fa-envelope" aria-hidden="true"></i>
<a href="https://docs.google.com/document/d/1E65ePNEtdPm-f0BjjZN7RnOAzFzaW1RXS_hcn-Y8_Ls/edit?usp=sharing">
<i class="fa fa-file-text" aria-hidden="true"></i>
</a>  


**Fausto Rodríguez Zapata** PhD Student. NCSU Genetics program  
Fausto studies maize glycerolipid quantitative and population genetics and genetic associations with soil variables involved in phosphorus deficiency.  
<a href="https://twitter.com/chyscamuy">
<i class="fa fa-twitter" aria-hidden="true"></i>
</a>  <a href="https://github.com/faustovrz">
<i class="fa fa-github-alt" aria-hidden="true"></i>
</a>

### Team in México   

**Elohim Bello**. PhD Student *co-advised with Luis Herrera-Estrella*  
Elohim studies natural variation of root soil penetration using Arabidopsis.   

**Jessica Carcaño** *Administrative assistant*.  
Jessy helps to run our lab and Ruairidh Sawers' and Stewart Gillmor´s labs.    

**Jonathan Ojeda**. PhD Student *co-advised with Luis Herrera-Estrella*.  
Jonathan is studying an Arabidopsis mutant that shows indeterminate primary root growth in low Phosphorus conditions.    
<a href="https://twitter.com/jonojedarivera">
<i class="fa fa-twitter" aria-hidden="true"></i>
</a>  

**Fabián Santa Maria** Master Student *co-advised with Luis Delaye*.   
Fabian works on *xipotl* genes, involved in phosphatydilcholine biosynthesis and in *opr7/opr8* involved in jasmonic acid biosynthesis   
<!-- break -->
<br><br><br>
<!-- break -->


### Former lab members  


**Patricio Cid** *Field Manager*.  
Patricio directed all the field operations of our lab and of ours and Sawers' labs.  

**Juan Estévez** *Wet Lab Manager*.  
Juan ran all the big genotyping, GBSing and cloning of our and Sawers´ labs.  

**Karla Juarez** *Master Student*.   
Karla studied the role of phospholipids in maize adaptation to low phosphorus and low temperature.  

**Sofía Estefany Sánchez** Master Student *co-advised with Ruairidh Sawers*. Sofía worked with the *xipotl* family of genes in maize a set of genes that are involved in the methylation pathway of phosphatidylcholine.  

**Vladimir Torres**. Master Student *co-advised with Ruairidh Sawers*.    
Vladimir studied how an introgression of Teosinte parviglumis in B73 affects root growth and phoshorus deficiency. He is currently doing his PhD with Ruairidh Sawers.  

**Christian Escoto**. Master Student *co-advised with Ruairidh Sawers*.   
Christian worked in the analysis of different morphological traits affected by Phosphorus deficiency using a CML228 x B73 RIL mapping population.  

**Dario Alávez**. Dario worked as lab and field tech mainly developing a collection of Uniform-Mu mutants targetting a number of glycerolipid sysnthesis and degradation genes.
