---
title: Publications
pagetitle: Publications
output: html_document
---


---



Complete list of publications can be found at [Google Scholar](https://scholar.google.com.mx/citations?user=hdSIEUAAAAAJ&hl=en). Journal names have been intentionally excluded. Lab member names are in bold. Links are provided to the published article and, if publisher does not offer free access, a pdf of the final version. Links to code if available are also provided.
Click on the arrows to see a brief summary of what we did in the paper!

## Preprints 

### 2021

<details>
    <summary>
**31** [Demonstration of local adaptation of maize landraces by reciprocal transplantation](https://www.biorxiv.org/content/10.1101/2021.03.25.437076v1).  
Garrett M. Janzen, María Rocío Aguilar-Rangel, Carolina Cíntora-Martínez, **Karla Azucena Blöcher-Juárez**, Eric González-Segovia, Anthony J. Studer, Daniel E. Runcie, Sherry A. Flint-Garcia, **Rubén Rellán-Álvarez**, Ruairidh J. H. Sawers, Matthew B. Hufford </summary>
 <p style="margin-left: 30px">Using a panel of highland and lowland landraces from Mesoamerica and South America grown in highland and lowland common gardens in México we show local adaptation of maize landraces </p></details>  

<details>
    <summary>
**30** [Teosinte introgression modulates phosphatidylcholine levels and induces early maize flowering time
](https://www.biorxiv.org/content/10.1101/2021.01.25.426574v1).  
**Fausto Rodríguez-Zapata**, **Allison C Barnes**, **Karla A Blöcher-Juárez**, Dan Gates, **Andi Kur**, Li Wang, Garrett M Janzen, Sarah Jensen, **Juan M Estévez-Palmas**, Taylor Crow, Rocío Aguilar-Rangel, Edgar Demesa-Arevalo, Tara Skopelitis, Sergio Pérez-Limón, Whitney L Stutts, Peter Thompson, Yu-Chun Chiu, David Jackson, Oliver Fiehn, Daniel Runcie, Edward S Buckler, Jeffrey Ross-Ibarra, Matthew B. Hufford, Ruairidh JH Sawers and **Rubén Rellán-Álvarez** </summary>
 <p style="margin-left: 30px">Using genomic scans,linkage maping, lipidomics we identified *HPC1* a teosinte *mexicana* introgression gene encoding a phospholipase that leads to high levels of phosphotydilcholine and reduces flowering time  </p></details>  


### 2020    

<details>
    <summary>
**29** [Molecular Parallelism Underlies Convergent Highland Adaptation of Maize Landraces
](https://www.biorxiv.org/content/10.1101/2020.07.31.227629v1).  
Li Wang, Emily B. Josephs, Kristin M. Lee, Lucas M. Roberts, **Rubén Rellán-Álvarez**, Jeffrey Ross-Ibarra, Matthew B. Hufford </summary>
 <p style="margin-left: 30px">Maize has adapted to highland environments independently several times. In this study we studied highland adaptation in four highland groups: SWUSA, Mexican Highlands, Guatemalan Highlands and Andes and identified outlier genes involved in highland adaptation </p></details>

<details>
    <summary>
**28** [Single-gene resolution of locally adaptive genetic variation in Mexican maize](https://www.biorxiv.org/content/10.1101/706739v1).  
Daniel J Gates, Dan Runcie, Garrett M. Janzen, Alberto Romero Navarro, Martha Willcox, Kai Sonder, Samantha J. Snodgrass, **Fausto Rodríguez-Zapata**, Ruairidh J. H. Sawers, **Rubén Rellán-Álvarez**, Edward S. Buckler, Sarah Hearne, Matthew B. Hufford, Jeffrey Ross-Ibarra </summary>
 <p style="margin-left: 30px">In this collaboration with the Ross-Ibarra lab we show that some of our candidate genes involved in determining glycerolipid concentrations overlap identified environmental GWAS and plant peformance by genotype interactions in panel 4000 landraces that were top-crossed and evaluated in several environments in Mexico</p></details>    

## Publications.

### 2020
<details>
    <summary>
**27** [Gene regulatory effects of a large chromosomal inversion in highland maize
](https://journals.plos.org/plosgenetics/article?id=10.1371/journal.pgen.1009213).  
Taylor Crow, James Ta, Saghi Nojoomi, M. Rocío Aguilar-Rangel, Jorge Vladimir Torres Rodrǵuez, Daniel Gates, **Ruben Rellan-Alvarez**, Ruairidh Sawers, Daniel Runcie </summary>
 <p style="margin-left: 30px">*Inv4m* is a 13 Mb inversion on chr4 in maize that is the result of highland teosinte mexicana in highland maize. This inversion is suppossed to have contributed to maize adaptation to highlands. Using a combination of association mapping and transcriptomics using NILs containing the highland inverted haplotype in a B73 background we study the role of *Inv4m* in several fitness traits and identify possible adpative candidates genes within the inversion  </p></details>

### 2019  
<details>
    <summary>
**26** [Inoculation with the mycorrhizal fungus *Rhizophagus irregularis* modulates the relationship between root growth and nutrient content in maize (*Zea mays ssp. mays* L.)](https://onlinelibrary.wiley.com/doi/full/10.1002/pld3.192).  
Flores-Ramirez R, **Elohim Bello-Bello**, **Rellán-Álvarez R**, Sawers R., Olalde-Portugal V </summary>
 <p style="margin-left: 30px">We studied the interaction of nutrient uptake with arbuscular mycorrhizal symbiosis. Most nutrients showed a correlation of nutrient uptake with enhanced root growth due to mycorrhizal colonization but some nutrients like P accumulated to levels that are indicative of an active fungal delivery to the roots</p></details>

### 2017

<details>
    <summary>
**25** [Coordinated changes in the accumulation of metal ions in maize (*Zea mays ssp. mays L.*) in response to inoculation with the arbuscular mycorrhizal fungus *Funneliformis mosseae*](https://academic.oup.com/pcp/article-abstract/doi/10.1093/pcp/pcx100/4060515/Co-ordinated-Changes-in-the-Accumulation-of-Metal?redirectedFrom=fulltext).  
Flores-Ramirez R, **Rellán-Álvarez R**, Wozniak B, Gebreselassie M-F, Jakobsen I, Olalde-Portugal V, Baxter I, Paszkowski U, Sawers R.</summary>
 <p style="margin-left: 30px">We study the effect of mycorrizhal colonization on the ionome of a maize diversity panel a found patterns of coordinated changes among ions with similar biochemical properties </p></details>

**24** [Morphological plant modeling: Unleashing geometric and topological potential within the plant sciences](http://journal.frontiersin.org/article/10.3389/fpls.2017.00900/abstract).  
Bucksch A, Atta-Boateng A, Fortune Azihou A, Balduzzi M, Battogtokh D, Baumgartner A, Binder B, Braybrook S, Chang C, Coneva V, DeWitt T, Fletcher A, Gehan M, Hernan Diaz Martinez D, Hong L, Iyer-Pascuzzi A, Klein L, Leiboff S, Li M, Lynch J, Maizel A, Maloof J, Markelz RJ, Martinez C, Miller L, Mio W, Palubicki W, Poorter H, Pradal C, Price C, Puttonen E, Reese J, **Rellán-Alvarez R**, Spalding E, Sparks E, Topp C, Williams J, Chitwood D.

**23** [Malate-dependent Fe accumulation is a critical checkpoint in the root developmental response to low phosphate](http://www.pnas.org/content/114/17/E3563)  
Mora-Macias J, **Odilon Ojeda-Rivera J**, Gutierrez-Alanis D, Yong-Villalobos L, Oropeza-Aburto A, Raya-González J, Jiménez-Doménguez G, Chavez-Calvillo G, ** Rellán-Álvarez R**, Herrera-Estrella LR.

### 2016

**22** [Grasses suppress shoot-borne roots to conserve water during drought](http://www.pnas.org/content/113/31/8861.full)  
Sebastian J, Yee M-C, Goudinho Viana W, **Rellán-Álvarez R**, Feldman M, Priest HD, Trontin C, Lee T, Jiang H, Baxter I, Mockler TC, Hochholdinger F, Brutnell TP, Dinneny JR.

**21** [Plant scientists:GM technology is safe](http://science.sciencemag.org/content/351/6275/824.1) [[Github repo]](https://github.com/nfahlgren/plant_scientists_support_gmo/blob/master/submitted_article.md).  
Fahlgren N, Bart R, Herrera-Estrella L, **Rellán-Álvarez R**, Chitwood DH, Dinneny JR.  

**20** [Environmental control of Root System Biology](http://arjournals.annualreviews.org/eprint/IZTJBGTdd3P8yv4MCmFP/full/10.1146/annurev-arplant-043015-111848).  
**Rellán-Álvarez R**, Lobet G, Dinneny J.R.

### 2015

**19** [GLO-Roots: an imaging platform enabling multidimensional characterization of soil-grown roots systems](http://dx.doi.org/10.7554/eLife.07597). [[Github repo]](https://github.com/rr-lab/GLO-Roots).  
**Rellán-Álvarez R**, Lobet G, Hildner H, Pradier PL, Sebastian J, Yee MC, Yu G, La Rue T, Trontin C, Schrager A, Haney C, Nieu R, Maloof J, Vogel J, Dinneny JR

### 2013

**18** [Iron-dependent modifications of the flower transcriptome, proteome, metabolome and hormonal content in an Arabidopsis ferritin mutant](http://jxb.oxfordjournals.org/content/early/2013/05/15/jxb.ert112.abstract).  
Sudre D, Gutiérrez-Carbonell E, Lattanzio G, **Rellán-Álvarez R**, Gaymard F, Wohlgemuth G, Fiehn O, Álvarez Fernández A, Zamarreño AM, Bacaicoa E, Duy D, Garcíamina JM, Abadía J, Philippar K, López-Millán AF, Briat JF.

### 2012

**17** [New functions of nicotianamine in the phloem-based transport of iron to sink organs, in pollen development and in pollen tube growth](www.plantcell.org/content/24/6/2380.abstract).  
Schüler M, **Rellán-Álvarez R**, Fink-Straube C, Abadía J, Petra Bauer.

**16** [Oxidative stress is a consequence, not a cause, of aluminum toxicity in the forage legume Lotus corniculatus](http://onlinelibrary.wiley.com/doi/10.1111/j.1469-8137.2011.03978.x/abstract).  
Navascués J, Pérez-Rontomé C, Sánchez DH, Staudinger C, Wienkoop S, **Rellán- Álvarez R**, Becana M.

### 2011

**15** [Metabolite profile changes in xylem sap and leaves of Strategy I plants in response to iron deficiency and iron resupply](http://www.frontiersin.org/Plant_Nutrition/10.3389/fpls.2011.00066/abstract).  
**Rellán-Álvarez R**, El Jendoubi H, Wohlgemuth G, Fiehn O, Abadía A, Abadía J, Álvarez Fernández A.

**14** [Development of a new high-performance liquid chromatography electrospray ionization time-of-flight mass spectrometry method for the determination of low molecular mass organic acids in plant tissue extracts](http://pubs.acs.org/doi/abs/10.1021/jf200482a). [[PDF]](pdfs/14-2011-rra.pdf)  
**Rellán-Álvarez R**, López-Gomollón S, Abadía J, Álvarez-Fernández A.  

**13** [Towards a knowledge-based correction of iron chlorosis](http://www.sciencedirect.com/science/article/pii/S0981942811000428). [[PDF]](pdfs/13-2011-abadia.pdf)    
Abadía J, Vázquez S, **Rellán-Álvarez R**, El Jendoubi H, Abadía A, Álvarez- Fernández A, López-Millán AF.

**12** [Carboxylate metabolism in sugar beet plants grown with excess Zn](http://www.sciencedirect.com/science/article/pii/S0176161710005511). [[PDF]](pdfs/12-2011-sagardoy.pdf)  
Sagardoy R, Morales F, **Rellán-Álvarez R**, Abadía A, Abadía J, López-Millán AF.

**11** [Metabolic response in roots of Prunus rootstocks submitted to iron chlorosis](http://www.sciencedirect.com/science/article/pii/S0176161710004165).  
Jiménez S, Ollat N, Deborde C, Maucourt M, **Rellán-Álvarez R**, Moreno MA, Gogorcena Y.

### 2010

**10** [Changes in the proteomic and metabolic profiles of Beta vulgaris root tips in response to iron deficiency and resupply](http://www.biomedcentral.com/1471-2229/10/120).  
**Rellán-Álvarez R**, Andaluz S, Rodríguez-Celma J, Wohlgemuth G, Zocchi G, Álvarez-Fernández A, Fiehn O, López-Millán AF, Abadía J.

**9** [Changes induced by two levels of cadmium toxicity in the 2-DE protein profile of tomato roots](http://www.sciencedirect.com/science/article/pii/S1874391910001351). [[PDF]](pdfs/09-2010-rod-celma.pdf)  
Rodríguez-Celma J, **Rellán-Álvarez R**, Abadía A, Abadía J, López-Millán AF.

**8** [Growth, yield and fruit quality of pepper plants amended with two sanitized sewage sludges](http://pubs.acs.org/doi/abs/10.1021/jf100282f). [[PDF]](pdfs/08-2010-pascual.pdf)
Pascual I, Azcona I, Aguirreolea J, Morales F, Corpas FJ, Palma JM **Rellán-Álvarez R**, Sánchez-Díaz M. G.  

**7** [Identification of a tri-iron(III), tri-citrate complex in the xylem sap of iron-deficient tomato resupplied with iron: new insights into plant iron long-distance transport](http://pcp.oxfordjournals.org/content/51/1/91.long).  
**Rellán-Álvarez R**, Giner-Martínez-Sierra J, Orduna J, Orera I, Rodríguez- Castrillón JA, García-Alonso JI, Abadía J, Álvarez-Fernández A.

### 2009

**6** [Effect of oil refinery sludges on the growth and antioxidant system of alfalfa plants](http://www.sciencedirect.com/science/article/pii/S0304389409010152). [[PDF]](pdfs/06-2009-marti.pdf)  
Martí MC, Camejo D, Fernández-García N, **Rellán-Álvarez R**, Marques S, Sevilla F, Jiménez A.

### 2008

**5** [Formation of metal- nicotianamine complexes as affected by pH, ligand exchange with citrate and metal exchange. A study by electrospray ionization time-of-flight mass spectrometry](http://onlinelibrary.wiley.com/doi/10.1002/rcm.3523/abstract). [[PDF]](pdfs/05-2008-rra.pdf)  
**Rellán-Álvarez R**, Abadía J, Álvarez-Fernández A.

### 2007

**4** [Rapid alteration of cellular redox homeostasis upon exposure to cadmium and mercury in alfalfa seedlings](http://onlinelibrary.wiley.com/doi/10.1111/j.1469-8137.2007.02162.x/full).  
Ortega-Villasante C, Hernández LE, **Rellán-Álvarez R**, Del Campo FF, Carpena- Ruíz RO.

### 2006

**3** [Direct and simultaneous determination of reduced and oxidized glutathione and homoglutathione by liquid chromatography-electrospray/mass spectrometry in plant tissue extracts](http://www.sciencedirect.com/science/article/pii/S0003269706004015). [[PDF]](pdfs/03-2006-rra.pdf)  
**Rellán-Álvarez R**, Hernández LE, Abadía J, Álvarez-Fernández A.

**2** [Stress responses of *Zea mays* to cadmium and mercury](http://rd.springer.com/article/10.1007/s11104-005-3900-1). [[PDF]](pdfs/02-2006-rra.pdf)  
**Rellán-Álvarez R**, Ortega-Villasante C,Álvarez-Fernández A, Del Campo FF, Hernández LE.

### 2005

**1** [Cellular damage induced by cadmium and mercury in Medicago sativa](http://jxb.oxfordjournals.org/content/56/418/2239.abstract).  
Ortega-Villasante C, **Rellán-Álvarez R**, Del Campo FF, Carpena-Ruíz RO, Hernández LE.
